# Generated by Django 2.2.4 on 2020-01-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.IntegerField(blank=True, max_length=4, null=True)),
                ('pdf_link', models.URLField(blank=True, max_length=250, null=True)),
                ('page_link', models.URLField(blank=True, max_length=250, null=True)),
                ('author', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
